
train_size: 0.9


################################################################
# features
################################################################

label_name: SalePrice

date_features:
  - saledate


################################################################
# models
################################################################

RandomForestRegressor:
  n_estimators: 100
  max_depth: 6
  min_samples_split: 2
  min_samples_leaf: 100
  max_features: 'auto'
  bootstrap: True
  # oob_score: True
  n_jobs: -1
  random_state: 42